name: Release

on:
  push:
    tags:
      - v**

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_to_crates_io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run
